name: Context testing
on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-20.04
    steps:
      - name: show functions
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startsWith('hello', 'he') }}
          echo ${{ endsWith('hello', 'lo') }}
          echo ${{ format('Hello {0} {1} {0}', 'World', '!') }}
  
  conditionals:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: push event
        run: echo "The triggering event was a push"

  dump_contexts_to_log:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: eccho '${{ toJSON(job) }}'
        continue-on-error: true
      - name: Dump steps context
      # can use job status function to force jobs to run after failed steps
        if: failure()
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always()
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'