name: Matrix
on: 
  push:
    tags:
      - disable

jobs:
  node-version: 
    strategy:
      matrix: 
      # run the job 3x, once for each version
        node_version: [6, 8, 10]
        # now we have a 3x3 matrix- job will run 9x with each n_v and os combination
        os: [macos-latest, ubuntu-latest, windows-latest]
        # fine-tune configurations
        exlude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: [6, 8]
        include:
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
      # if f-f, means that if one job in matrix fails, all others will stop
      # if not f-f, each 3 jobs run independent of results of the other jobs, even if one fails
      #fail-fast: true
      # by default GH tries to run as many in parallel as possible (with 0?) but can limit
      #max-parallel: 2
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{matrix.is_ubuntu_8}}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
        # reference matrix context
          node-version: ${{ matrix.node_version }}
      - name: Log node version again
        run: | 
          node -v
          echo $IS_UBUNTU_8
