name: Shell commands
on: [push, pull_request] # can be single or an [array]
# an object with a key for each job
jobs:
  run-shell-command:
    # specify OS
    runs-on: ubuntu-latest
    steps: # array of objects for each step
      - name: echo a string
        run: eccho "Hello Tara"
      - name: multiline script
        run: |
          node -v
          npm -v