name: Shell commands
on: [pull_request_review_comment] # can be single or an [array]
# an object with a key for each job
jobs:
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  run-shell-command:
    # specify OS
    runs-on: ubuntu-latest
    # specify jobs that should finish successfully first (dependencies)
    needs: ["run-windows-command"]
    steps: # array of objects for each step
      - name: echo a string
        run: echo "Hello Tara"
      - name: multiline script
        run: |
          node -v
          npm -v
      # using a different shell:
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python